spring.application.name=ECOMM_Cart_Service_Application
server.port=8085

jwt.secret=very-secure-and-very-long-secret-key-at-least-32-chars-long

#Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379